services:
  - type: web
    name: hr-sage-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers=2 --timeout=500
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: GOOGLE_DRIVE_CREDENTIALS_JSON
        sync: false
