name: GEE Export Every 5 Days

# 1) schedule: runs every 5 days at midnight UTC
# 2) workflow_dispatch: allows manual trigger from Actions tab
on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      # Step 1: Check out your repo
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Python dependencies (include pandas)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install earthengine-api google-auth google-api-python-client pandas gspread oauth2client supabase

      # Step 4: Write service account JSON
      - name: Write service account JSON
        run: echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS_JSON }}' > sa.json

      # Step 5: Authenticate and initialize Earth Engine
      - name: Set up Earth Engine
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
        run: |
          python backend/gee_export.py

      # Step 6: Run update script to merge CSVs into Sheet
      - name: Trigger update_sheet script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
        run: |
          python backend/update_sheet.py
