name: GEE Export Every 5 Days

on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repo
      - uses: actions/checkout@v3

      # Step 2: Set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 3: Install Python dependencies (include pandas)
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install earthengine-api google-auth google-api-python-client pandas gspread oauth2client supabase

      # Step 4: Write service account JSON to expected path
      - name: Write service account JSON
        run: |
          mkdir -p backend/data
          echo '${{ secrets.GOOGLE_DRIVE_CREDENTIALS_JSON }}' > backend/data/service-account.json

      # Step 5: Authenticate and initialize Earth Engine
      - name: Run gee_export script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/backend/data/service-account.json
        run: |
          python backend/gee_export.py

      # Step 6: Run update script to merge CSVs into Sheet and push to Supabase
      - name: Run update_sheet script
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/backend/data/service-account.json
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          python backend/update_sheet.py
