name: GEE Export Every 5 Days

# 1) schedule: runs every 5 days at midnight UTC
# 2) workflow_dispatch: allows manual trigger from Actions tab
on:
  schedule:
    - cron: "0 0 */5 * *"
  workflow_dispatch:

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      # Step 2.1: check out your repo
      - uses: actions/checkout@v3

      # Step 2.2: set up Python
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      # Step 2.3: install dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install earthengine-api google-auth google-api-python-client

      # Step 2.4: write your service-account.json from the secret
      - name: Decode service account JSON
        run: |
          echo "${{ secrets.GCP_SA_JSON }}" > ${GITHUB_WORKSPACE}/sa.json

      # Step 2.5: authenticate Earth Engine
      - name: Set up Earth Engine
        run: |
          echo "${{ secrets.GOOGLE_DRIVE_CREDENTIALS_JSON }}" > sa.json
          python backend/gee_export.py
        env:
          GOOGLE_APPLICATION_CREDENTIALS: sa.json

      # Step 2.6: run your export script
      - name: Trigger GEE export
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/sa.json
        run: |
          python backend/update_sheet.py
